# Generated by Django 2.1.7 on 2019-03-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200, verbose_name='店')),
                ('url', models.CharField(max_length=200, verbose_name='URL')),
                ('address', models.CharField(max_length=200, verbose_name='住所')),
                ('phone_number', models.CharField(max_length=200, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_name', models.CharField(max_length=200, verbose_name='ライブ')),
                ('open_time', models.DateTimeField(verbose_name='オープン')),
                ('start_time', models.DateTimeField(verbose_name='スタート')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curator.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=200, verbose_name='プレイヤー')),
                ('instrument', models.CharField(max_length=200, verbose_name='楽器')),
            ],
        ),
        migrations.AddField(
            model_name='live',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curator.Player'),
        ),
    ]
